export const CONTANT_ADD_REQEST = 'CONTANT_ADD_REQEST'
export const CONTANT_ADD_SUCCESS = 'CONTANT_ADD_SUCCESS'
export const CONTANT_ADD_FAIL = 'CONTANT_ADD_FAIL'

export const GET_ALL_CONTANT_REQEST = 'GET_ALL_CONTANT_REQEST'
export const GET_ALL_CONTANT_SUCCESS = 'GET_ALL_CONTANT_SUCCESS'
export const GET_ALL_CONTANT_FAIL = 'GET_ALL_CONTANT_FAIL'
export const GET_ALL_CONTANT_RESET = 'GET_ALL_CONTANT_RESET'